name: Build and deploy Python app with React to Azure Web App

on:
  push:
    branches:
      - dev-js
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Set up Node.js to build React
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install Node.js dependencies and build the React app
      - name: Install Node.js dependencies and build React app
        run: |
          cd frontend
          npm install
          npm run build

      # Copy React build files to Flask's static directory
      - name: Copy React build files to Flask static directory
        run: |
          cp -r frontend/build/static/css static/
          cp -r frontend/build/static/js static/
          cp frontend/build/index.html static/public/index.html

      # Set up virtual environment for Python
      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      # Install Python dependencies
      - name: Install Python dependencies
        run: pip install -r requirements.txt

      # Zip the application for deployment
      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      # Upload the artifact for deployment
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      # Download the artifact from the build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      # Unzip the artifact for deployment
      - name: Unzip artifact for deployment
        run: unzip release.zip

      # Deploy to Azure Web App
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'sucafina-we-impact-webapp-01'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_FF6DD760D0824573A1BC7701A5844A47 }}
