name: Build and deploy Python app to Azure Web App - sucafina-we-impact-webapp-01

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Node.js to build the frontend React app
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Install frontend dependencies with --legacy-peer-deps
      - name: Install frontend dependencies with --legacy-peer-deps
        working-directory: ./static
        run: npm install --legacy-peer-deps

      # Build frontend React app
      - name: Build frontend React app
        working-directory: ./static
        run: npm run build

      # Set up Python to deploy the Flask backend
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install backend dependencies
        run: pip install -r requirements.txt

      # Move the built React files to Flask's static/public folder
      - name: Move React build to Flask static/public folder
        run: |
          rm -rf ./static/public/*
          mv ./static/build/* ./static/public/

      # Zip artifact for deployment
      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'sucafina-we-impact-webapp-01'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3DC7750C2DB749A5B2D6CA777E3B025D }}